### ISSUE TITLE
[Fabric] Terra incompatible with memory optimization mods (ferrite/hydrogen)

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [PolyhedralDev/Terra#148]
I tried running terra using both [Hydrogen](https://modrinth.com/mod/hydrogen/versions) and [Ferritecore](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric) and both resulted in a crash.

```
01.05 13:47:46 [Server] main/INFO [STDOUT]: Terra Compatibility Module initialized.
01.05 13:48:13 [Server] main/FATAL Failed to start the minecraft server
01.05 13:48:13 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terra'!
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[custom.jar:?]
01.05 13:48:13 [Server] INFO at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
01.05 13:48:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [custom.jar:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
01.05 13:48:13 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
01.05 13:48:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [custom.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [custom.jar:?]
01.05 13:48:13 [Server] INFO Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract com.google.common.collect.ImmutableSet createKeySet()' of abstract class com.google.common.collect.ImmutableMap.
01.05 13:48:13 [Server] INFO at com.google.common.collect.ImmutableMap.keySet(ImmutableMap.java:728) ~[Geyser-Fabric-1.3.0-SNAPSHOT.jar:?]
01.05 13:48:13 [Server] INFO at net.minecraft.class_2688.method_28501(class_2688.java:85) ~[intermediary-server.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.fabric.world.FabricAdapter.adapt(FabricAdapter.java:62) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.fabric.world.FabricWorldHandle.createBlockData(FabricWorldHandle.java:23) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.fabric.world.FabricWorldHandle.createBlockData(FabricWorldHandle.java:15) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.registry.config.FloraRegistry.create(FloraRegistry.java:55) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.registry.config.FloraRegistry.<init>(FloraRegistry.java:19) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:158) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:46) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:36) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at com.dfsek.terra.fabric.TerraFabricPlugin.onInitialize(TerraFabricPlugin.java:311) ~[Terra-fabric-5.2.0-BETA+eee54f50-shaded-mapped.jar:?]
01.05 13:48:13 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[custom.jar:?]
01.05 13:48:13 [Server] INFO ... 17 more
```

**Comment by dfsek** [comment]
This does not appear to be an issue with either Hydrogen or FerriteCore, but with Geyser-Fabric. I was unable to find the specific version you have, but the version I did find, `1.0-SNAPSHOT`, also seems to have this issue, it's because they shade a different version of `com.google.common` than what Minecraft contains, and do not relocate it. Report this to them.
