### ISSUE TITLE
[Bug] Terra is not generating world

### ISSUE THREAD

**Issue by AsP3X** [PolyhedralDev/Terra#209]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | Terra v4.0.0-BETA+213182e
| Platform / Platform Version  | PaperMC 1.16.5 - papermc-762-1.16.5
| Any External Plugins or Mods | multiverse-core, essentialsx
| Terra Packs In Use           | default
| Terra Addons In Use          | none

## Issue Description

When starting the server the plugin tries to initialize but spits out following error:
com.dfsek.tectonic.exception.LoadException: Failed to load value "biomes" to field "providerBuilder": Value "biomes" was not found in the provided config.

### Steps to reproduce

1. Setting up a server from scratch and starting it to initialize all nesessary files.
2. Stopping server and copying all mentioned plugins
3. Restarting the server
4. ERROR

### Expected behavior

The plugin initializes and loads default and nether config

### Actual behavior

Crashes and logs error:

### Full stacktrace

<details>

```log
[Terra] Loading ZIP archive: default.zip
[18:15:04] [Server thread/WARN]: com.dfsek.tectonic.exception.LoadException: Failed to load value "noise" to field "noiseBuilderMap": Unable to load object.
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:206)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:136)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:152)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.registry.ConfigRegistry.load(ConfigRegistry.java:45)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.registry.ConfigRegistry.loadAll(ConfigRegistry.java:35)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.command.ReloadCommand.execute(ReloadCommand.java:33)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.Command.onCommand(Command.java:97)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.Command.onCommand(Command.java:84)
[18:15:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:15:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:15:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827)
[18:15:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[18:15:04] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Unable to load object.
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:27)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadClass(ConfigLoader.java:276)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:32)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:17)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:23)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:12)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
[18:15:04] [Server thread/WARN]:        ... 18 more
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Failed to load value "type" to field "type": Unexpected exception thrown during type loading: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:206)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:25)
[18:15:04] [Server thread/WARN]:        ... 26 more
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Unexpected exception thrown during type loading: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:270)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
[18:15:04] [Server thread/WARN]:        ... 28 more
[18:15:04] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:240)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.api.math.noise.samplers.FastNoiseLite$NoiseType.valueOf(FastNoiseLite.java:2588)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.GenericLoaders.lambda$register$4(GenericLoaders.java:92)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        ... 29 more
[18:15:04] [Server thread/INFO]: [Terra] Loading ZIP archive: nether.zip
[18:15:04] [Server thread/WARN]: com.dfsek.tectonic.exception.LoadException: Failed to load value "noise" to field "noiseBuilderMap": Unable to load object.
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:206)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:136)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:152)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.registry.ConfigRegistry.load(ConfigRegistry.java:45)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.registry.ConfigRegistry.loadAll(ConfigRegistry.java:35)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.command.ReloadCommand.execute(ReloadCommand.java:33)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.Command.onCommand(Command.java:97)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.bukkit.command.Command.onCommand(Command.java:84)
[18:15:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:15:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:15:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827)
[18:15:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129)
[18:15:04] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[18:15:04] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Unable to load object.
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:27)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadClass(ConfigLoader.java:276)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:32)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.loaders.config.sampler.NoiseSamplerBuilderLoader.load(NoiseSamplerBuilderLoader.java:17)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:23)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:12)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
[18:15:04] [Server thread/WARN]:        ... 18 more
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Failed to load value "type" to field "type": Unexpected exception thrown during type loading: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:206)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:250)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:25)
[18:15:04] [Server thread/WARN]:        ... 26 more
[18:15:04] [Server thread/WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Unexpected exception thrown during type loading: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:270)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:190)
[18:15:04] [Server thread/WARN]:        ... 28 more
[18:15:04] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: No enum constant com.dfsek.terra.api.math.noise.samplers.FastNoiseLite.NoiseType.FBm
[18:15:04] [Server thread/WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:240)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.api.math.noise.samplers.FastNoiseLite$NoiseType.valueOf(FastNoiseLite.java:2588)
[18:15:04] [Server thread/WARN]:        at com.dfsek.terra.config.GenericLoaders.lambda$register$4(GenericLoaders.java:92)
[18:15:04] [Server thread/WARN]:        at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:265)
[18:15:04] [Server thread/WARN]:        ... 29 more
[18:15:04] [Server thread/INFO]: Errors occurred while reloading Terra configurations. See logs for more information.
```
</details>

### Additional details

Even custom packs are resulting in the same error

**Comment by dfsek** [comment]
* You're using a *very* outdated version
* You're using a ***very*** outdated config, even for that version.


Did you even read the issue template?
