### ISSUE TITLE
cant load default.zip

### ISSUE THREAD

**Issue by nueafa** [PolyhedralDev/Terra#216]
[15:30:26 ERROR]: [Terra] Failed to load config pack from ZIP archive "plugins\Terra\packs\default.zip"
[15:30:26 ERROR]: Error occurred while enabling Terra v5.3.3-BETA+5dd00db8 (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: minecraft:dirt_path
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.createNewData(CraftBlockData.java:532) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-777]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2236) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2229) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1743) ~[patched_1.16.5.jar:git-Paper-777]
        at com.dfsek.terra.bukkit.handles.BukkitWorldHandle.createBlockData(BukkitWorldHandle.java:19) ~[?:?]
        at com.dfsek.terra.api.structures.script.functions.PullFunction.<init>(PullFunction.java:30) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:12) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseFunction(Parser.java:414) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:360) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseStatementBlock(Parser.java:156) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseIfStatement(Parser.java:139) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseLoopLike(Parser.java:103) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:356) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseBlock(Parser.java:342) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parse(Parser.java:88) ~[?:?]
        at com.dfsek.terra.api.structures.script.StructureScript.<init>(StructureScript.java:101) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.lambda$load$8(ConfigPack.java:231) ~[?:?]
        at com.dfsek.terra.config.fileloaders.Loader.thenEntries(Loader.java:37) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.load(ConfigPack.java:228) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:190) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:46) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:36) ~[?:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:183) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:dirt_path' at position 0: <--[HERE]

**Comment by Fallstop** [comment]
Sorry to reuse a closed, badly written, issue, but we are currently experiencing this bug on 1.17. Do you believe that the errors:

```
[18:14:03] [Server thread/INFO]: [Terra] Loading config pack "DEFAULT"
[18:14:04] [Server thread/ERROR]: [Terra] Failed to load config pack from ZIP archive "plugins\Terra\packs\default.zip"
[18:14:04] [Server thread/ERROR]: Error occurred while enabling Terra v5.3.3-BETA+5dd00db8 (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: minecraft:grass_path
```
is caused by your plugin, or just some other conflict on our side?
(just it is hard to tell if it is invalid because it isn't from your plugin, or it's invalid because there is no content or help from the issue).

**Comment by RuofengX** [comment]
I got exactly same issue in paper 1.16.5
`[18:50:31 INFO]: [Terra] Enabling Terra v5.4.1-BETA+efd1665c
[18:50:31 INFO]: [Terra] Running on version V1_16
[18:50:31 INFO]: [Terra] Loading config values
[18:50:31 INFO]: [Terra] DebugLogger: true
[18:50:31 INFO]: [Terra] /mnt/datadisk0/oasis0/plugins/Terra/lang/zh_cn.yml
[18:50:31 INFO]: [Terra] Loaded language zh_cn
[18:50:31 INFO]: [Terra] Loading ZIP archive: default.zip
[18:50:31 INFO]: [Terra] Loading config pack "DEFAULT"
[18:50:32 ERROR]: [Terra] Failed to load config pack from ZIP archive "plugins/Terra/packs/default.zip"
[18:50:32 ERROR]: Error occurred while enabling Terra v5.4.1-BETA+efd1665c (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: minecraft:dirt_path
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.createNewData(CraftBlockData.java:532) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-777]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2236) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2229) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1743) ~[patched_1.16.5.jar:git-Paper-777]
        at com.dfsek.terra.bukkit.handles.BukkitWorldHandle.createBlockData(BukkitWorldHandle.java:19) ~[?:?]
        at com.dfsek.terra.api.structures.script.functions.PullFunction.<init>(PullFunction.java:30) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:12) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseFunction(Parser.java:414) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:360) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseStatementBlock(Parser.java:156) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseIfStatement(Parser.java:139) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseLoopLike(Parser.java:103) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:356) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseBlock(Parser.java:342) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parse(Parser.java:88) ~[?:?]
        at com.dfsek.terra.api.structures.script.StructureScript.<init>(StructureScript.java:101) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.lambda$load$8(ConfigPack.java:231) ~[?:?]
        at com.dfsek.terra.config.fileloaders.Loader.thenEntries(Loader.java:37) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.load(ConfigPack.java:228) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:190) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:46) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:36) ~[?:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:184) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:dirt_path' at position 0: <--[HERE]
[18:50:32 INFO]: [Terra] Disabling Terra v5.4.1-BETA+efd1665c`

**Comment by RuofengX** [comment]
I solve it by using version 5.3.3-BETA.
Maybe 5.4.1 didn't support 1.16.5
