### ISSUE TITLE
[Bug] Game crashes with a null pointer exception when loading a Terra world any time after the first

### ISSUE THREAD

**Issue by PugsRCute385** [PolyhedralDev/Terra#230]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version               | Terra-fabric-5.4.1-BETA+40e95073-shaded-mapped
| Platform / Platform Version  | Fabric Loader 0.11.3, 1.17 
| Any External Plugins or Mods | Architectury 2.0.11, Cloth API 2.0.54, Cloth Config 5.0.34, Fabric API 0.36.0 1.17, Modmenu 2.0.2
| Terra Packs In Use           | Default
| Terra Addons In Use          | N/A

## Issue Description

When loading a world generated with Terra:Default any time after the first, the game crashes and throws a null value exception.

### Steps to reproduce

1. Created a survival world with Terra:default world type
2. Explored a bit on a boat
3. Found a mountain and climbed it
4. Restarted game to apply different audio output (system)
5. Tried to load up the world again
6. The chunk generating loading screen is shown as expected
7. Game crashes with null pointer exception
7. Created another survival world with Terra:default world type
8. Did not explore far but made a base around spawnpoint
9. Closed game and shut off computer
10. (next day) Opened up Minecraft and tried to load (newer) the world
11. Chunk loading screen is shown as expected
12. Game crashed with same exception as before
13. Happens every time

### Expected behavior

The world should load up and not crash as soon as loading.

### Actual behavior

When I load the world, it crashes every time.

### Full stacktrace
[latest.log](https://github.com/PolyhedralDev/Terra/files/6720539/latest.log)
-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1948.method_27819(class_1948.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_3215.method_27907(class_3215.java:391)
	at net.minecraft.class_1948.method_27815(class_1948.java:162)
	at net.minecraft.class_3215.method_14161(class_3215.java:347)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,69,64), Section: (at 0,5,0 in 1,4,4; chunk contains blocks 16,0,64 to 31,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 191124 game time, 217606 day time
	Level name: Terra Survival
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 84126 (now: false), thunder time: 146370 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

</details>

### Additional details

- N/A

**Comment by limelier** [comment]
I also encounter this issue. However, it only occurs with Terra 5.4.1. Downgrading to 5.3.3 and generating a new world does not produce the same issue.

**Comment by TAKfsg** [comment]
I also encountered this issue as well

**Comment by tioalexis** [comment]
Encountering the same issue with `Terra-fabric-5.4.1-BETA+40e95073-shaded-mapped.jar` even when the only mods active are terra and the fabric api (0.40.0+1.17)
