### ISSUE TITLE
[Bug] Server crash when generating : y out of range

### ISSUE THREAD

**Issue by CleryJa** [PolyhedralDev/Terra#256]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 5.4.1 & 5.3.3
| Platform / Platform Version  | PaperSpigot 1.16.5 - 786 / Purpur 1.16.5-1171
| Any External Plugins or Mods | WorldEdit
| Terra Packs In Use           | Custom pack (can provide copy in private if needed : aDaxxas#1234)
| Terra Addons In Use          | None

## Issue Description

When generating terrain, the server crashes

### Steps to reproduce

1. Boot the server
2. Explore in spectator mode
3. Wait for crash

### Expected behavior

No crash :(

### Actual behavior

The server crash :(

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```
[16:21:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R3.ReportedException: Exception ticking world
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1505) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: y out of range (expected 0-255, got 256)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:363) ~[patched_1.16.5.jar:git-Paper-786]
	at org.bukkit.craftbukkit.v1_16_R3.CraftChunk.getBlock(CraftChunk.java:100) ~[patched_1.16.5.jar:git-Paper-786]
	at com.dfsek.terra.bukkit.world.BukkitChunk.getBlock(BukkitChunk.java:34) ~[?:?]
	at com.dfsek.terra.world.population.items.tree.TreeLayer.place(TreeLayer.java:23) ~[?:?]
	at com.dfsek.terra.world.population.TreePopulator.populate(TreePopulator.java:46) ~[?:?]
	at com.dfsek.terra.bukkit.population.PopulationManager.lambda$checkNeighbors$0(PopulationManager.java:69) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.dfsek.terra.bukkit.population.PopulationManager.checkNeighbors(PopulationManager.java:67) ~[?:?]
	at com.dfsek.terra.bukkit.population.PopulationManager.populate(PopulationManager.java:88) ~[?:?]
	at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:891) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1057) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1235) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:672) ~[patched_1.16.5.jar:git-Paper-786]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-786]
	... 5 more
```
</details>

### Additional details

I hope this is not because of my pack :S I didn't find anything in the error about an error in it 

I am providing logs for the different version as I tested the issue with the following setups : 

- PaperSpigot & Terra 5.3.3
- PaperSpigot & Terra 5.4.1
- Purpur & Terra 5.4.1

[latest - paper & 5.3.3.log](https://github.com/PolyhedralDev/Terra/files/6988295/latest.-.paper.5.3.3.log)
[latest purpur & 5.4.1.log](https://github.com/PolyhedralDev/Terra/files/6988296/latest.purpur.5.4.1.log)
[latest paper & 5.4.1.log](https://github.com/PolyhedralDev/Terra/files/6988297/latest.paper.5.4.1.log)

**Comment by xKsyStudio** [comment]
My server also crashed using 5.4.1 (Use WorldBorder to fill) It crashed 8 times
Paper1.17.1

**Comment by solonovamax** [comment]
please provide the seed you used for this, and the coordinates at which it crashed

**Comment by xKsyStudio** [comment]
-
[crash-2021-08-23_01.04.21-server.txt](https://github.com/PolyhedralDev/Terra/files/7027995/crash-2021-08-23_01.04.21-server.txt)
[crash-2021-08-23_02.27.26-server.txt](https://github.com/PolyhedralDev/Terra/files/7027996/crash-2021-08-23_02.27.26-server.txt)
[crash-2021-08-23_00.15.55-server.txt](https://github.com/PolyhedralDev/Terra/files/7027997/crash-2021-08-23_00.15.55-server.txt)
