### ISSUE TITLE
[Bug] Plugin crashes on load 

### ISSUE THREAD

**Issue by cfitz25** [PolyhedralDev/Terra#258]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 5.4.1
| Platform / Platform Version  | git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
| Any External Plugins or Mods | None
| Terra Packs In Use           | None
| Terra Addons In Use          | None

## Issue Description

The generator crashes on load.

### Steps to reproduce

1. Install plugin
2. Start server

### Expected behavior

Plugin to load.

### Actual behavior

Plugin does not load.

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```
Patching vanilla jar...
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.2+7) Host: Linux 5.12.19-1-MANJARO (amd64)
Loading libraries, please wait...
[16:24:53 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:24:53 INFO]: Found new data pack file/bukkit, loading it automatically
[16:24:53 INFO]: Reloading ResourceManager: Default, bukkit
[16:24:54 INFO]: Loaded 7 recipes
[16:24:55 INFO]: Starting minecraft server version 1.16.5
[16:24:55 INFO]: Loading properties
[16:24:55 INFO]: This server is running Paper version git-Paper-786 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[16:24:55 INFO]: Server Ping Player Sample Count: 12
[16:24:55 INFO]: Using 4 threads for Netty based IO
[16:24:55 INFO]: Debug logging is disabled
[16:24:55 INFO]: Default game type: SURVIVAL
[16:24:55 INFO]: Generating keypair
[16:24:56 INFO]: Starting Minecraft server on *:25565
[16:24:56 INFO]: Using epoll channel type
[16:24:57 INFO]: [Terra] Loaded addon Terra-Bukkit v1.0.0, by Terra
[16:24:57 INFO]: [Terra] Loading Terra v5.4.1-BETA+efd1665c
[16:24:57 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:24:57 INFO]: [Terra] Enabling Terra v5.4.1-BETA+efd1665c
[16:24:57 INFO]: [Terra] Running on version V1_16
[16:24:57 INFO]: [Terra] Loading config values
[16:24:57 INFO]: [Terra] DebugLogger: false
[16:24:57 INFO]: [Terra] /media/cupiditas/SSD-Big/cupiditas/Documents/minecraft/AngelServer/plugins/Terra/lang/en_us.yml
[16:24:57 INFO]: [Terra] Loaded language en_us
[16:24:57 INFO]: [Terra] Loading config pack "DEFAULT"
[16:24:57 ERROR]: [Terra] Failed to load config pack from ZIP archive "plugins/Terra/packs/default.zip"
[16:24:57 ERROR]: Error occurred while enabling Terra v5.4.1-BETA+efd1665c (Is it up to date?)
java.lang.IllegalArgumentException: Could not parse data: minecraft:dirt_path
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.createNewData(CraftBlockData.java:532) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-786]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:507) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2237) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:2230) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1743) ~[patched_1.16.5.jar:git-Paper-786]
        at com.dfsek.terra.bukkit.handles.BukkitWorldHandle.createBlockData(BukkitWorldHandle.java:19) ~[?:?]
        at com.dfsek.terra.api.structures.script.functions.PullFunction.<init>(PullFunction.java:30) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.api.structures.script.builders.PullFunctionBuilder.build(PullFunctionBuilder.java:12) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseFunction(Parser.java:414) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:360) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseStatementBlock(Parser.java:156) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseIfStatement(Parser.java:139) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseLoopLike(Parser.java:103) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseItem(Parser.java:356) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parseBlock(Parser.java:342) ~[?:?]
        at com.dfsek.terra.api.structures.parser.Parser.parse(Parser.java:88) ~[?:?]
        at com.dfsek.terra.api.structures.script.StructureScript.<init>(StructureScript.java:101) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.lambda$load$8(ConfigPack.java:231) ~[?:?]
        at com.dfsek.terra.config.fileloaders.Loader.thenEntries(Loader.java:37) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.load(ConfigPack.java:228) ~[?:?]
        at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:190) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:46) ~[?:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:36) ~[?:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:184) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:dirt_path' at position 0: <--[HERE]
[16:24:57 INFO]: [Terra] Disabling Terra v5.4.1-BETA+efd1665c
[16:24:57 INFO]: Preparing level "world"
[16:24:57 ERROR]: Could not set generator for default world 'world': Plugin 'Terra v5.4.1-BETA+efd1665c' is not enabled yet (is it load:STARTUP?)
[16:24:57 INFO]: -------- World Settings For [world] --------
[16:24:57 INFO]: Experience Merge Radius: 6.0
[16:24:57 INFO]: Cactus Growth Modifier: 100%
[16:24:57 INFO]: Cane Growth Modifier: 100%
[16:24:57 INFO]: Melon Growth Modifier: 100%
[16:24:57 INFO]: Mushroom Growth Modifier: 100%
[16:24:57 INFO]: Pumpkin Growth Modifier: 100%
[16:24:57 INFO]: Sapling Growth Modifier: 100%
[16:24:57 INFO]: Beetroot Growth Modifier: 100%
[16:24:57 INFO]: Carrot Growth Modifier: 100%
[16:24:57 INFO]: Potato Growth Modifier: 100%
[16:24:57 INFO]: Wheat Growth Modifier: 100%
[16:24:57 INFO]: NetherWart Growth Modifier: 100%
[16:24:57 INFO]: Vine Growth Modifier: 100%
[16:24:57 INFO]: Cocoa Growth Modifier: 100%
[16:24:57 INFO]: Bamboo Growth Modifier: 100%
[16:24:57 INFO]: SweetBerry Growth Modifier: 100%
[16:24:57 INFO]: Kelp Growth Modifier: 100%
[16:24:57 INFO]: Entity Activation Range: An 16 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:24:57 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:24:57 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:24:57 INFO]: Max TNT Explosions: 100
[16:24:57 INFO]: Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
[16:24:57 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:24:57 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:24:57 INFO]: View Distance: 10
[16:24:57 INFO]: Item Merge Radius: 3.5
[16:24:57 INFO]: Item Despawn Rate: 6000
[16:24:57 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:24:57 INFO]: Zombie Aggressive Towards Villager: true
[16:24:57 INFO]: Nerfing mobs spawned from spawners: false
[16:24:57 INFO]: Mob Spawn Range: 10
[16:25:01 INFO]: -------- World Settings For [world_nether] --------
[16:25:01 INFO]: Experience Merge Radius: 6.0
[16:25:01 INFO]: Cactus Growth Modifier: 100%
[16:25:01 INFO]: Cane Growth Modifier: 100%
[16:25:01 INFO]: Melon Growth Modifier: 100%
[16:25:01 INFO]: Mushroom Growth Modifier: 100%
[16:25:01 INFO]: Pumpkin Growth Modifier: 100%
[16:25:01 INFO]: Sapling Growth Modifier: 100%
[16:25:01 INFO]: Beetroot Growth Modifier: 100%
[16:25:01 INFO]: Carrot Growth Modifier: 100%
[16:25:01 INFO]: Potato Growth Modifier: 100%
[16:25:01 INFO]: Wheat Growth Modifier: 100%
[16:25:01 INFO]: NetherWart Growth Modifier: 100%
[16:25:01 INFO]: Vine Growth Modifier: 100%
[16:25:01 INFO]: Cocoa Growth Modifier: 100%
[16:25:01 INFO]: Bamboo Growth Modifier: 100%
[16:25:01 INFO]: SweetBerry Growth Modifier: 100%
[16:25:01 INFO]: Kelp Growth Modifier: 100%
[16:25:01 INFO]: Entity Activation Range: An 16 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:25:01 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:25:01 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:25:01 INFO]: Max TNT Explosions: 100
[16:25:01 INFO]: Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
[16:25:01 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:25:01 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:25:01 INFO]: View Distance: 10
[16:25:01 INFO]: Item Merge Radius: 3.5
[16:25:01 INFO]: Item Despawn Rate: 6000
[16:25:01 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:25:01 INFO]: Zombie Aggressive Towards Villager: true
[16:25:01 INFO]: Nerfing mobs spawned from spawners: false
[16:25:01 INFO]: Mob Spawn Range: 10
[16:25:01 WARN]: Unable to find spawn biome
[16:25:02 INFO]: -------- World Settings For [world_the_end] --------
[16:25:02 INFO]: Experience Merge Radius: 6.0
[16:25:02 INFO]: Cactus Growth Modifier: 100%
[16:25:02 INFO]: Cane Growth Modifier: 100%
[16:25:02 INFO]: Melon Growth Modifier: 100%
[16:25:02 INFO]: Mushroom Growth Modifier: 100%
[16:25:02 INFO]: Pumpkin Growth Modifier: 100%
[16:25:02 INFO]: Sapling Growth Modifier: 100%
[16:25:02 INFO]: Beetroot Growth Modifier: 100%
[16:25:02 INFO]: Carrot Growth Modifier: 100%
[16:25:02 INFO]: Potato Growth Modifier: 100%
[16:25:02 INFO]: Wheat Growth Modifier: 100%
[16:25:02 INFO]: NetherWart Growth Modifier: 100%
[16:25:02 INFO]: Vine Growth Modifier: 100%
[16:25:02 INFO]: Cocoa Growth Modifier: 100%
[16:25:02 INFO]: Bamboo Growth Modifier: 100%
[16:25:02 INFO]: SweetBerry Growth Modifier: 100%
[16:25:02 INFO]: Kelp Growth Modifier: 100%
[16:25:02 INFO]: Entity Activation Range: An 16 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:25:02 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:25:02 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[16:25:02 INFO]: Max TNT Explosions: 100
[16:25:02 INFO]: Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
[16:25:02 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:25:02 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:25:02 INFO]: View Distance: 10
[16:25:02 INFO]: Item Merge Radius: 3.5
[16:25:02 INFO]: Item Despawn Rate: 6000
[16:25:02 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[16:25:02 INFO]: Zombie Aggressive Towards Villager: true
[16:25:02 INFO]: Nerfing mobs spawned from spawners: false
[16:25:02 INFO]: Mob Spawn Range: 10
[16:25:02 WARN]: Unable to find spawn biome
[16:25:03 INFO]: Preparing start region for dimension minecraft:overworld
[16:25:03 INFO]: Preparing spawn area: 0%
[16:25:03 INFO]: Time elapsed: 396 ms
[16:25:03 INFO]: Preparing start region for dimension minecraft:the_nether
[16:25:03 INFO]: Preparing spawn area: 0%
[16:25:04 INFO]: Preparing spawn area: 0%
[16:25:04 INFO]: Time elapsed: 518 ms
[16:25:04 INFO]: Preparing start region for dimension minecraft:the_end
[16:25:04 INFO]: Preparing spawn area: 0%
[16:25:04 INFO]: Preparing spawn area: 0%
[16:25:04 INFO]: Time elapsed: 718 ms
[16:25:05 INFO]: Running delayed init tasks
[16:25:05 INFO]: Done (9.402s)! For help, type "help"
[16:25:05 INFO]: Timings Reset

```

</details>

### Additional details

[latest.log](https://github.com/PolyhedralDev/Terra/files/7025041/latest.log)

**Comment by Roan-V** [comment]
Terra versions 5.4.1 and above package a version of the default configuration designed for 1.17. This default config uses 1.17 blocks and items, and will not run on older versions.

To run on 1.16, you must either:
    - Download an older version of the mod/plugin (version 5.3.3 is the latest 1.16 version) and re-generate the default config
	- or, download/make a pack made with 1.16 blocks, e.g. an older version of the default pack.

**Comment by solonovamax** [comment]
Closing because latest terra version does not run on 1.16.5.
