### ISSUE TITLE
[Bug] Game crashes when I open a previously made terra world

### ISSUE THREAD

**Issue by NotAMonke** [PolyhedralDev/Terra#276]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                |5.4.1 
| Platform / Platform Version  |Fabric 
| Any External Plugins or Mods |N/A
| Terra Packs In Use           |N/A 
| Terra Addons In Use          |N/A 

## Issue Description

 When I try to open a world I previously made terra:default, my game crashes. I'm only able to play when I first create and enter the world.

### Steps to reproduce

 I had a separate fabric profile made that doesn't use the default game directory. This mod was the only mod in the mods folder.

1.  I downloaded and put terra into my fabric profile's mods folder.
2.  I booted up minecraft and made a terra style world. This worked just fine.
3.  I quit to title and tried to open the world again. This resulted in my game crashing.

### Expected behavior

 I should've been able to open the world again and play like normal.

### Actual behavior

 My game simply crashed.
 When I have this mod installed, I cannot play on a world more than once.

### Full stacktrace

<details> Note: I'm not very good with the technical side of the game. I may have gotten this part wrong. I'll add a few parts from the log just in case
<summary>Exception Stacktrace</summary>

```
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1959.method_30966()" because the return value of "net.minecraft.class_1948.method_27822(net.minecraft.class_2338, net.minecraft.class_2791)" is null
	at net.minecraft.class_1948.method_27819(class_1948.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_3215.method_27907(class_3215.java:392)
	at net.minecraft.class_1948.method_27815(class_1948.java:162)
	at net.minecraft.class_3215.method_14161(class_3215.java:348)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1948.method_27819(class_1948.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_3215.method_27907(class_3215.java:392)
	at net.minecraft.class_1948.method_27815(class_1948.java:162)
	at net.minecraft.class_3215.method_14161(class_3215.java:348)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,87,160), Section: (at 0,7,0 in -1,5,10; chunk contains blocks -16,0,160 to -1,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 480 game time, 480 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 56546 (now: false), thunder time: 85889 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 786481000 bytes (750 MiB) / 1879048192 bytes (1792 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: LuminonCore IDDCX Adapter
	Graphics card #0 vendor: LuminonCore
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.2018.1204
	Graphics card #1 name: NVIDIA GeForce GTX 1660
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2184
	Graphics card #1 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 13754.16
	Virtual memory used (MB): 10418.78
	Swap memory total (MB): 5632.00
	Swap memory used (MB): 100.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'



<!--
If Terra logs an exception, please put it in the following section: (You will find any error logs in your console, or your latest.log)
Note: this *must* be included, in ADDITION to the latest.log file.
-->Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1959.method_30966()" because the return value of "net.minecraft.class_1948.method_27822(net.minecraft.class_2338, net.minecraft.class_2791)" is null
	at net.minecraft.class_1948.method_27819(class_1948.java:163)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_3215.method_27907(class_3215.java:392)
	at net.minecraft.class_1948.method_27815(class_1948.java:162)
	at net.minecraft.class_3215.method_14161(class_3215.java:348)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>

### Additional details

 Thank you for responding to my previous post so quickly.

**Comment by dfsek** [comment]
#230
