### ISSUE TITLE
[Bug] Server crash with creating world (1.18.1)

### ISSUE THREAD

**Issue by ReferTV** [PolyhedralDev/Terra#286]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                |  Terra-bukkit-6.0.0-BETA+77d341eba-shaded
| Platform / Platform Version  | Paper Build #81
| Any External Plugins or Mods | N/A
| Terra Packs In Use           | default
| Terra Addons In Use          | N-A -->

### Steps to reproduce

    1. Setup server and bukkit.yml
    2. Run server
    3. I'm get error.

### Expected behavior

Correct world creation without errors

### Actual behavior

Server crashing

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```
[12:02:02] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:02:02] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[12:02:02] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[12:02:03] [Worker-Main-3/INFO]: Loaded 7 recipes
[12:02:04] [Server thread/INFO]: Starting minecraft server version 1.18.1
[12:02:04] [Server thread/WARN]: ****************************
[12:02:04] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[12:02:04] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[12:02:04] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[12:02:04] [Server thread/WARN]: ****************************
[12:02:04] [Server thread/INFO]: Loading properties
[12:02:04] [Server thread/INFO]: This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
[12:02:04] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:02:04] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:02:04] [Server thread/INFO]: Default game type: SURVIVAL
[12:02:04] [Server thread/INFO]: Generating keypair
[12:02:04] [Server thread/INFO]: Starting Minecraft server on *:30000
[12:02:04] [Server thread/INFO]: Using epoll channel type
[12:02:04] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[12:02:04] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Initializing Terra...
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.config.PluginConfigImpl] Loading config values from config.yml
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Loading 22 Terra addons:
        - biome-provider-image@0.1.0-BETA+77d341eba
        - biome-provider-pipeline@0.1.0-BETA+77d341eba
        - biome-provider-single@0.1.0-BETA+77d341eba
        - chunk-generator-noise-3d@0.1.0-BETA+77d341eba
        - config-biome@0.1.0-BETA+77d341eba
        - config-distributors@0.1.0-BETA+77d341eba
        - config-feature@0.1.0-BETA+77d341eba
        - config-flora@0.1.0-BETA+77d341eba
        - config-locators@0.1.0-BETA+77d341eba
        - config-noise-function@0.1.0-BETA+77d341eba
        - config-ore@0.1.0-BETA+77d341eba
        - config-palette@0.1.0-BETA+77d341eba
        - config-structure@0.1.0-BETA+77d341eba
        - generation-stage-feature@0.1.0-BETA+77d341eba
        - generation-stage-structure@0.1.0-BETA+77d341eba
        - language-yaml@0.1.0-BETA+77d341eba
        - palette-block-shortcut@0.1.0-BETA+77d341eba
        - structure-block-shortcut@0.1.0-BETA+77d341eba
        - structure-function-check-noise-3d@0.1.0-BETA+77d341eba
        - structure-sponge-loader@0.1.0-BETA+77d341eba
        - structure-terrascript-loader@0.1.0-BETA+77d341eba
        - terra@1.0.0
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Terra addons successfully loaded.
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.commands.CommandUtil] Registering Terra commands...
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Finished initialization.
[12:02:04] [Server thread/INFO]: [Terra] Loading Terra v6.0.0-BETA+77d341eba
[12:02:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:02:04] [Server thread/INFO]: [Terra] Enabling Terra v6.0.0-BETA+77d341eba
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.bukkit.TerraBukkitPlugin] Running on Minecraft version v1.18.1 with server implementation Paper.
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Loading config packs...
[12:02:04] [Server thread/INFO]: [com.dfsek.terra.registry.master.ConfigRegistry] Loading ZIP archive: default.zip
[12:02:05] [Server thread/INFO]: [com.dfsek.terra.config.pack.ConfigPackImpl] Loading config pack "OVERWORLD"
[12:02:06] [Server thread/INFO]: [com.dfsek.terra.config.pack.ConfigPackImpl] Loaded config pack "OVERWORLD" v0.1.0 by Astrash, Sancires in 1807.723401ms.
[12:02:06] [Server thread/INFO]: [com.dfsek.terra.AbstractPlatform] Loaded packs.
[12:02:06] [Server thread/INFO]: [com.dfsek.terra.commands.CommandUtil] Registering Terra commands...
[12:02:06] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[12:02:06] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[12:02:06] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[12:02:06] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[12:02:06] [Server thread/INFO]: Preparing level "world"
[12:02:08] [Server thread/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$34(ChunkMap.java:1226) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1260) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:671) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:532) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:472) ~[?:?]
	at net.minecraft.server.level.PlayerRespawnLogic.getOverworldRespawnPos(PlayerRespawnLogic.java:23) ~[?:?]
	at net.minecraft.server.level.PlayerRespawnLogic.getSpawnPosInChunk(PlayerRespawnLogic.java:64) ~[?:?]
	at net.minecraft.server.MinecraftServer.setInitialSpawn(MinecraftServer.java:809) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:746) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:696) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Coordinates -7, 48, 16 are not in the region
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftLimitedRegion.getBlockData(CraftLimitedRegion.java:162) ~[paper-1.18.1.jar:git-Paper-81]
	at com.dfsek.terra.bukkit.world.BukkitProtoWorld.getBlockState(BukkitProtoWorld.java:52) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:107) ~[?:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:57) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$0(FeatureGenerationStage.java:59) ~[?:?]
	at com.dfsek.terra.api.structure.feature.BinaryColumn.forEach(BinaryColumn.java:34) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:57) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:52) ~[?:?]
	at com.dfsek.terra.bukkit.generator.BukkitChunkGeneratorWrapper$1.populate(BukkitChunkGeneratorWrapper.java:74) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:408) ~[paper-1.18.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:275) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1211) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.1.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1209) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[12:02:08] [Server thread/FATAL]: Failed to schedule load callback for chunk [0, 0]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$35(ChunkMap.java:1228) ~[paper-1.18.1.jar:git-Paper-81]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.1.jar:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$37(ChunkMap.java:1209) ~[paper-1.18.1.jar:git-Paper-81]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalArgumentException: Coordinates -7, 48, 16 are not in the region
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftLimitedRegion.getBlockData(CraftLimitedRegion.java:162) ~[paper-1.18.1.jar:git-Paper-81]
	at com.dfsek.terra.bukkit.world.BukkitProtoWorld.getBlockState(BukkitProtoWorld.java:52) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:107) ~[?:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:57) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$0(FeatureGenerationStage.java:59) ~[?:?]
	at com.dfsek.terra.api.structure.feature.BinaryColumn.forEach(BinaryColumn.java:34) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:57) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:52) ~[?:?]
	at com.dfsek.terra.bukkit.generator.BukkitChunkGeneratorWrapper$1.populate(BukkitChunkGeneratorWrapper.java:74) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:408) ~[paper-1.18.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:275) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1211) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.1.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1209) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
[12:02:08] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:760) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:696) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Coordinates -7, 48, 16 are not in the region
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftLimitedRegion.getBlockData(CraftLimitedRegion.java:162) ~[paper-1.18.1.jar:git-Paper-81]
	at com.dfsek.terra.bukkit.world.BukkitProtoWorld.getBlockState(BukkitProtoWorld.java:52) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:107) ~[?:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:57) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$0(FeatureGenerationStage.java:59) ~[?:?]
	at com.dfsek.terra.api.structure.feature.BinaryColumn.forEach(BinaryColumn.java:34) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:57) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:52) ~[?:?]
	at com.dfsek.terra.bukkit.generator.BukkitChunkGeneratorWrapper$1.populate(BukkitChunkGeneratorWrapper.java:74) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:408) ~[paper-1.18.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:275) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1211) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.1.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1209) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[12:02:08] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalArgumentException: Coordinates -7, 48, 16 are not in the region
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftLimitedRegion.getBlockData(CraftLimitedRegion.java:162) ~[paper-1.18.1.jar:git-Paper-81]
	at com.dfsek.terra.bukkit.world.BukkitProtoWorld.getBlockState(BukkitProtoWorld.java:52) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:107) ~[?:?]
	at com.dfsek.terra.addons.ore.ores.VanillaOre.generate(VanillaOre.java:57) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$0(FeatureGenerationStage.java:59) ~[?:?]
	at com.dfsek.terra.api.structure.feature.BinaryColumn.forEach(BinaryColumn.java:34) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:57) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:52) ~[?:?]
	at com.dfsek.terra.bukkit.generator.BukkitChunkGeneratorWrapper$1.populate(BukkitChunkGeneratorWrapper.java:74) ~[Terra-bukkit-6.0.0-BETA+77d341eba-shaded.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:408) ~[paper-1.18.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:275) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1211) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.1.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1209) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:02:08] [Server thread/ERROR]: This crash report has been saved to: /home/serwer/./crash-reports/crash-2021-12-19_12.02.08-server.txt
[12:02:08] [Server thread/INFO]: Stopping server
[12:02:08] [Server thread/INFO]: [Terra] Disabling Terra v6.0.0-BETA+77d341eba
[12:02:08] [Server thread/INFO]: Saving players
[12:02:08] [Server thread/INFO]: Saving worlds
[12:02:08] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:02:08] [Server thread/INFO]: Flushing Chunk IO
[12:02:08] [Server thread/INFO]: Closing Thread Pool
```

</details>

### Additional details

N/A

**Comment by dfsek** [comment]
fixed in 30f7f002d58db93796cf826454ed9f1f9d8d71f4, will now warn on out-of-bounds access rather than crash.

**Comment by ReferTV** [comment]
Now I have spam error of this
[latest.log](https://github.com/PolyhedralDev/Terra/files/7741630/latest.log)
.

**Comment by dfsek** [comment]
read the closing comment.

**Comment by ReferTV** [comment]
Oh, sorry. And how to get rid of these warnings? Because I can't enter the server
