### ISSUE TITLE
Terra Not Loaded

### ISSUE THREAD

**Issue by NixonSiagian** [PolyhedralDev/Terra#321]
## Describe the issue

[03:23:30] [Server thread/ERROR]: [Terra] Could not set generator for default world 'world': Plugin 'Terra v6.1.1-BETA+d93f11b5f
java.lang.IllegalArgumentException: No such config pack "OVERWORLD"
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$1(TerraBukkitPlugin.java:176) ~[Terra-bukkit-6.1.1-BETA+d93f11b5f-shaded.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$2(TerraBukkitPlugin.java:175) ~[Terra-bukkit-6.1.1-BETA+d93f11b5f-shaded.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.getDefaultWorldGenerator(TerraBukkitPlugin.java:174) ~[Terra-bukkit-6.1.1-BETA+d93f11b5f-shaded.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getGenerator(CraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:615) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411

**Comment by dfsek** [comment]
Terra 6 is for 1.18
