### ISSUE TITLE
[Bug] Game/Server crash when moving around

### ISSUE THREAD

**Issue by xSaVageAU** [PolyhedralDev/Terra#327]
## Pre-Issue Checklist

- [X] I have checked that I am on the latest version of Terra.
- [X] I have searched the github issue tracker for similar issues, including
  closed ones.
- [X] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [X] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  ]
- [X] I have attached a copy of the `latest.log` file
- [X] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 6.1.1
| Platform / Platform Version  | Fabric 1.14.8
| Any External Plugins or Mods | N/A
| Terra Packs In Use           | Default
| Terra Addons In Use          | N/A

## Issue Description
Server crashes when moving around / generating chunks on a Terra world. The issue is identical in single player. It can happen in as quick as 1 minute or up to 10-15 minutes.

### Steps to reproduce

1. Start a new world.
2. Enter creative mode and fly around.
3. Wait for a crash.

### Expected behavior
It should not be crashing (obviously).

### Actual behavior
The game/server crashes.

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 25/6/22, 12:11 am
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_3218.method_18203(class_3218.java:459)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_3218.method_18203(class_3218.java:459)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)

-- Thread dumps --
Details:
	Thread dumps: Server thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_3218.method_18203(class_3218.java:459)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_3218.method_18203(class_3218.java:459)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['xSaVage_'/71, l='ServerLevel[world]', x=667.55, y=125.46, z=-3661.34]]
	Chunk stats: 4313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10441 game time, 10441 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 135940 (now: false), thunder time: 105778 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 621915512 bytes (593 MiB) / 3300917248 bytes (3148 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37796.40
	Virtual memory used (MB): 24479.94
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx8G
	Server Running: true
	Player Count: 1 / 20; [class_3222['xSaVage_'/71, l='ServerLevel[world]', x=667.55, y=125.46, z=-3661.34]]
	Data Packs: vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

```

```

</details>

### Additional details
I was playing around for about an hour when I first installed the mod, mostly staying around the spawn area before it crashed the first time. It only seems to happen when generating new chunks. I also tried it on my home server in a VM with the same result.

[latest.log](https://github.com/PolyhedralDev/Terra/files/8977213/latest.log)

**Comment by obelouix** [comment]
Can confirm this on Paper/Purpur 1.19 too

**Comment by dfsek** [comment]
This has been fixed on Fabric in 34b1aca556fe54f1b630b97b9b1d131746e33887. I've not been able to replicate this on Paper/Purpur, are you using the latest builds?

I'll be keeping this open until 6.2 is released and this has been figured out on Bukkit.

**Comment by obelouix** [comment]
Yep, i'm using the latest builds. 

I noticed that this was more likely to happen when there are several people on the server, with only one player connected it rarely happens

**Comment by dfsek** [comment]
Reopening since this is still present on Bukkit servers (we are unable to fix it ourselves there)

Paper issue: PaperMC/Paper/issues/8116
