### ISSUE TITLE
NPE on Paper 1.16.4

### ISSUE THREAD

**Issue by ArtelGG** [PolyhedralDev/Terra#33]
This exception occurs when throwing an eye of ender in a non-Terra world with default settings (`/mvcreate example normal`). From what I can tell, this does not occur in Terra worlds.
Initially discovered on my survival server which has quite a few plugins so I went ahead and booted up a server which only had a few base plugins (`Terra`, `Chunky` and `Multiverse-Core` to be specific) and I was able to reproduce it there as well.

```
[07:02:00 ERROR]: Could not pass event EntitySpawnEvent to Terra v1.5.0-BETA+70ec483
java.lang.NullPointerException: null
        at com.dfsek.terra.TerraWorld.<init>(TerraWorld.java:30) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]
        at com.dfsek.terra.TerraWorld.getWorld(TerraWorld.java:87) ~[?:?]
        at com.dfsek.terra.EventListener.onEnderEye(EventListener.java:40) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-314]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-314]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-314]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-314]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntitySpawnEvent(CraftEventFactory.java:661) ~[patched_1.16.4.jar:git-Paper-314]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:636) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1187) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1083) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.ItemEnderEye.a(ItemEnderEye.java:83) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:379) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:414) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1609) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-314]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-314]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dfsek** [comment]
Fixed in 87cc2d01cb49807d54106dc21689bbd14d242a25
