### ISSUE TITLE
[Bug] Cant use 

### ISSUE THREAD

**Issue by loolksama** [PolyhedralDev/Terra#337]
com.dfsek.terra.event.FunctionalEventHandlerImpl] Exception occurred during event handling. Report this to the maintainers of terra@1.0.0
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Could not parse data: minecraft:mangrove_leaves[distance=1,persistent=false]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689) ~[?:?]
        at java.util.stream.Nodes.collect(Nodes.java:328) ~[?:?]
        at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:570) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$1(TerraScriptAddon.java:57) ~[?:?]
        at com.dfsek.terra.config.fileloaders.LoaderImpl.thenEntries(LoaderImpl.java:49) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$2(TerraScriptAddon.java:40) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:52) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1064) ~[?:?]
        at com.dfsek.terra.event.EventManagerImpl.callEvent(EventManagerImpl.java:38) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:174) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:135) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:77) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:67) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.AbstractPlatform.lambda$load$0(AbstractPlatform.java:152) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:55) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1064) ~[?:?]
        at com.dfsek.terra.event.EventManagerImpl.callEvent(EventManagerImpl.java:38) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:59) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Could not parse data: minecraft:mangrove_leaves[distance=1,persistent=false]
        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525) ~[patched_1.17.1.jar:git-Paper-411]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1219) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2417) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2410) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1874) ~[patched_1.17.1.jar:git-Paper-411]
        at com.dfsek.terra.bukkit.handles.BukkitWorldHandle.createBlockState(BukkitWorldHandle.java:42) ~[Terra-bukkit-6.2.0-BETA+7d056bd88-shaded.jar:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction$Constant.<init>(BlockFunction.java:97) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:37) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseFunction(Parser.java:453) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseItem(Parser.java:385) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseBlock(Parser.java:362) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parse(Parser.java:96) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.<init>(StructureScript.java:127) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$0(TerraScriptAddon.java:52) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1832) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149) ~[?:?]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:mangrove_leaves' at position 0: <--[HERE]
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] NMS bindings for version v1_17_R1 do not exist. Support for this version is limited.
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] This is usually due to running Terra on an unsupported Minecraft version.
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer]
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer]
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] PROCEEDING WITH AN EXISTING TERRA WORLD WILL RESULT IN CORRUPTION!!!
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer]
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer]
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] NMS bindings for version v1_17_R1 do not exist. Support for this version is limited.
[19:31:35 ERROR]: [com.dfsek.terra.bukkit.nms.Initializer] This is usually due to running Terra on an unsupported Minecraft version.
[19:33:49 WARN]: [Multiverse-Core] Failed to get the default chunk generator: java.lang.IllegalArgumentException: No such config pack "OVERWORLD"

**Comment by Astrashh** [comment]
Terra 6.2 is not compatible with 1.17, see https://terra.polydev.org/install/versions.html

**Comment by loolksama** [comment]
thx i get it

**Comment by imh3ro** [comment]
same thing happening in 1.18.2 too.
