### ISSUE TITLE
Terra:NETHER config pack not available

### ISSUE THREAD

**Issue by Arthurmeade12** [PolyhedralDev/Terra#346]
## Describe the issue
Terra's [config](https://terra.polydev.org/install/bukkit-server-world-creation.html) implies that a NETHER config pack is available:
```
Here is an example with two worlds configured:

bukkit.yml
 worlds:
   world:
     generator: Terra:OVERWORLD
   world_nether:
     generator: Terra:NETHER
```
However, Terra fails to find this config pack: 
```
[15:39:52 ERROR]: [Terra] Could not set generator for default world 'ctl_nether': Plugin 'Terra v6.1.2-BETA+9abac34b8
java.lang.IllegalArgumentException: No such config pack "NETHER"
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$1(TerraBukkitPlugin.java:176) ~[Terra-bukkit-6.1.2-BETA+9abac34b8-shaded.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$2(TerraBukkitPlugin.java:175) ~[Terra-bukkit-6.1.2-BETA+9abac34b8-shaded.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.getDefaultWorldGenerator(TerraBukkitPlugin.java:174) ~[Terra-bukkit-6.1.2-BETA+9abac34b8-shaded.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.getGenerator(CraftServer.java:1694) ~[purpur-1.19.jar:git-Purpur-1708]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:530) ~[purpur-1.19.jar:git-Purpur-1708]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1708]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1708]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1708]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1708]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Is the pack simply not packaged with Terra, despite what the config implies, or is this a bug?
Thank you for any help.

**Comment by Astrashh** [comment]
See https://terra.polydev.org/config/community-packs.html, previously a nether pack was bundled with v5 however this is no longer the case, the set up guide simply uses the `NETHER` pack id as an example.

**Comment by Arthurmeade12** [comment]
Is there a place where I can download the NETHER pack, or does it simply not exist for v6?
