### ISSUE TITLE
[Bug] Failed To Handle Packet

### ISSUE THREAD

**Issue by Brittank88** [PolyhedralDev/Terra#376]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including
  closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | `Terra-quilt-6.2.0-BETA+7d056bd88` |
| Platform / Platform Version  | `Quilt 0.4.4`, `Quilt Loader 0.17.6` |
| Any External Plugins or Mods | `anvilrestoration-fabric_1.19.2-1.7, architectury-6.3.49-fabric, AxesAreWeapons-1.6.0-fabric-1.17.1, badpackets-fabric-0.2.0, betterbeaconplacement-fabric_1.19.2-2.1, betterconduitplacement-fabric_1.19.2-2.0, bettersleeping-0.6.1+1.19, betterspawnercontrol-fabric_1.19.2-3.1, BetterThanMending-1.7.2, c2me-fabric-mc1.19.2-0.2.0+alpha.9.0, carpet-extra-1.19.1-1.4.83, chickensshed-1.19-1.3.3, Chunky-1.3.38, cloth-config-8.2.88-fabric, collective-fabric-1.19.2-5.11, colorfulanvils-1.0.2+1.19.1, crops_love_rain-1.3.0, cyanide-fabric-1.19-3.0.0, Debugify-2.7.1, deepslatecutting-fabric-1.5.0, discerning-furnace-1.0.9+MC1.19-1.19.2, dragondropselytra-fabric_1.19.2-2.0, DungeonsArise-1.19-2.1.51-fabric-beta-hf, Dynmap-3.4-fabric-1.19.1, easyelytratakeoff-fabric_1.19.2-3.2, EditSign-1.19.2-2.6.0, expanded-armor-enchanting-1.0.3, expanded-axe-enchanting-1.0.4, expanded-trident-enchanting-1.0.4, expanded-weapon-enchanting-1.0.3, extendedbonemeal-fabric_1.19.2-2.1, fabrication-3.1.1+1.19, fabricautocrafter-1.0.7, fabric-carpet-1.19.2-1.4.84+v221018, fabriccrossdimtpfix-0.3.1, fastback-0.7.3+1.19.2, fastgrowth-1.7, Fastload-1.2.1, ferritecore-5.0.0-fabric, FoxGlow-1.5.0+fabric1.19.2, global_packs-quilt-1.19.2-1.14.2_quilt, graves-2.1.2+1.19.2, grind-enchantments-1.6.4+1.19, healingcampfire-fabric_1.19.2-4.0, healthcare-1.2.0, hoetweaks-fabric_1.19.2-2.0, HorseBuff-1.19-2.0.1, image2map-0.3.0, infinitetrading-fabric_1.19.2-3.1, infinityfix-1.0.0, Infinity-Water-Bucket-Fabric-1.19-2.0.0, inventorytotem-fabric_1.19.2-2.1, journeymap-1.19.1-5.9.0beta2-fabric, jsst-1.19-0.1.4, krypton-0.2.1, lazydfu-0.1.3, leaves-us-in-peace-1.0.10+MC1.19-1.19.2, ledger-1.2.5, lithium-fabric-mc1.19.2-0.10.0, logcleaner-1.0.0, logprot-fabric-1.19.1-1.6, megane-8.3.0, memoryleakfix-1.19.1-0.7.0, milkallthemobs-fabric_1.19.2-2.2, mixintrace-1.1.1+1.17, nbtcrafting-2.2.2+mc1.19, nethermap-2.0.2-1.19.2, no-enchant-cap-2.1.3+1.19.x, nopryingeyes-1.19.2-v1.4.0, notenoughcrashes-4.1.8+1.19.2-fabric, phosphor-fabric-mc1.19.x-0.8.1, pingspam-1.3.1+1.19.2, player-pronouns-1.5.0+1.19, profundis-1.4.1, qfapi-4.0.0-beta.17_qsl-3.0.0-beta.19_fapi-0.64.0_mc-1.19.2, quiltgoslightlyfasterlol-0.0.3, quilt-kotlin-libraries-0.1.2-MODFEST+kt.1.7.10+flk.1.8.2, repurposed_structures_quilt-6.3.6+1.19.2, restart-server-1.0.0, RoughlyEnoughItems-9.1.555, servercore-1.3.2-1.19.2, servertick-mc1.19-1.7, servshred-1.0.8, slumber-1.0.0, smoothboot-fabric-1.19-1.7.1, spark-1.9.45-fabric, starbidous-portal-linking-fabric-1.0.0+1.19.2, styled-chat-2.0.1+1.19.2, tectonic-mod-mc1.19-v1.0.2, Terra-quilt-6.2.0-BETA+7d056bd88, thorium-1.3.2, tinkerers-smithing-1.0.1+nbtc2, toofast-1.19-1.0.0, totw_additions-1.2.3-1.19.x-fabric, Towns-and-Towers-1.19-1.8.2, treeharvester-fabric_1.19.2-5.8, '[Universal]CTOV-v3-1-2', '[Universal]Immersive_Structures_v2-0-3', viewdistancefix-1.19.2-1.0.0, whereisit-1.19-1.14.11, wither-cage-fix-1.0.15+MC1.19-1.19.2, wraith-silkspawners-1.1.2, wthit-quilt-5.13.3` |
| Terra Packs In Use           | `default` |
| Terra Addons In Use          | Only defaults but will still list: `Terra-command-structures-1.0.0-BETA+7d056bd88-all, Terra-generation-stage-feature-1.1.0-BETA+7d056bd88-all, Terra-biome-provider-extrusion-1.0.0-BETA+7d056bd88-all, Terra-config-biome-1.0.0-BETA+7d056bd88-all, Terra-generation-stage-structure-1.0.0-BETA+7d056bd88-all, Terra-biome-provider-image-1.0.0-BETA+7d056bd88-all, Terra-config-distributors-1.0.0-BETA+7d056bd88-all, Terra-language-yaml-1.0.0-BETA+7d056bd88-all, Terra-biome-provider-pipeline-1.0.1-BETA+7d056bd88-all, Terra-config-feature-1.0.0-BETA+7d056bd88-all, Terra-palette-block-shortcut-1.0.0-BETA+7d056bd88-all, Terra-biome-provider-single-1.0.0-BETA+7d056bd88-all, Terra-config-flora-1.0.0-BETA+7d056bd88-all, Terra-structure-block-shortcut-1.0.0-BETA+7d056bd88-all, Terra-biome-query-api-1.0.0-BETA+7d056bd88-all, Terra-config-locators-1.1.0-BETA+7d056bd88-all, Terra-structure-mutator-0.1.0-BETA+7d056bd88-all, Terra-chunk-generator-noise-3d-1.1.0-BETA+7d056bd88-all, Terra-config-noise-function-1.0.0-BETA+7d056bd88-all, Terra-structure-sponge-loader-1.0.0-BETA+7d056bd88-all, Terra-command-addons-1.0.0-BETA+7d056bd88-all, Terra-config-ore-1.0.0-BETA+7d056bd88-all, Terra-structure-terrascript-loader-1.1.0-BETA+7d056bd88-all, Terra-command-packs-1.0.0-BETA+7d056bd88-all, Terra-config-palette-1.0.0-BETA+7d056bd88-all, Terra-terrascript-function-check-noise-3d-1.0.0-BETA+7d056bd88-all, Terra-command-profiler-1.0.0-BETA+7d056bd88-all, Terra-config-structure-1.0.0-BETA+7d056bd88-all, Terra-terrascript-function-sampler-1.0.0-BETA+7d056bd88-all, Terra-api-addon-loader-0.1.0-BETA+7d056bd88-all, Terra-manifest-addon-loader-1.0.0-BETA+7d056bd88-all` |

### Steps to reproduce

I REALLY want to be able to fill this out properly, but upon typing out each command I've typed out in this session, I find that the error doesn't print again. Not sure how to reproduce.

### Expected behavior

No error.

### Actual behavior

Stack trace is printed to console.

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```
[10:27:43] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2805@77f4216d, suppressing error
java.lang.NullPointerException: Cannot invoke "com.dfsek.terra.api.config.ConfigPack.getRegistry(java.lang.Class)" because the return value of "com.dfsek.terra.api.world.ServerWorld.getPack()" is null
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
        at com.dfsek.terra.addons.commands.structure.StructureCommandAddon.getStructureRegistry(StructureCommandAddon.java:34) ~[?:?]
        at com.dfsek.terra.api.command.arguments.RegistryArgument$RegistryArgumentParser.suggestions(RegistryArgument.java:150) ~[Terra-quilt-6.2.0-BETA+7d056bd88.jar:?]
        at cloud.commandframework.arguments.DelegatingSuggestionsProvider.apply(DelegatingSuggestionsProvider.java:47) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.arguments.DelegatingSuggestionsProvider.apply(DelegatingSuggestionsProvider.java:33) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandTree.suggestionsForDynamicArgument(CommandTree.java:642) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:569) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:531) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:531) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:492) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.arguments.DelegatingCommandSuggestionEngine.getSuggestions(DelegatingCommandSuggestionEngine.java:77) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.CommandManager.suggest(CommandManager.java:218) ~[cloud-core-1.7.0.jar-6d0a8517-afd9-4083-bde4-93d9d6e3baca-nested.jar:?]
        at cloud.commandframework.brigadier.CloudBrigadierManager.buildSuggestions(CloudBrigadierManager.java:629) ~[cloud-brigadier-1.7.0.jar-18257076-829a-4873-8ffc-5622732eb745-nested.jar:?]
        at cloud.commandframework.brigadier.CloudBrigadierManager.lambda$constructCommandNode$26(CloudBrigadierManager.java:570) ~[cloud-brigadier-1.7.0.jar-18257076-829a-4873-8ffc-5622732eb745-nested.jar:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:598) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onRequestCommandCompletions(ServerPlayNetworkHandler:535) ~[?:?]
        at net.minecraft.network.packet.c2s.play.RequestCommandCompletionsC2SPacket.apply(RequestCommandCompletionsC2SPacket:29) ~[?:?]
        at net.minecraft.network.packet.c2s.play.RequestCommandCompletionsC2SPacket.apply(RequestCommandCompletionsC2SPacket:7) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.redirect$zib000$redirectExecuteTask(ThreadExecutor:521) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:14277) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cfj000$modifiedRunLoop(MinecraftServer:8894) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

</details>

### Additional details

[latest.log](https://mclo.gs/fOZcls6)

**Comment by solonovamax** [comment]
Interesting...

Afaik if the pack is null, the game shouldn't have started?

**Comment by Brittank88** [comment]
This error occurred after the server had already fully started and I was in it moving around and executing commands.

**Comment by solonovamax** [comment]
@Brittank88 yeah, I can tell because it's a command you executed which caused the crash

**Comment by Brittank88** [comment]
Weirdly though, I re-ran (specifically, re-typed in case it was the suggestion mechanic itself) every single command and could not get it to happen again.
