### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by jacklollz2** [PolyhedralDev/Terra#387]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including
  closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment
| Name                         | Value |
|------------------------------|-------|
| Terra Version                | Terra v6.2.1-BETA+358e09d05
| Platform / Platform Version  | git-Purpur-1862 (MC: 1.19.3)
| Any External Plugins or Mods |  
| Terra Packs In Use           | Default
| Terra Addons In Use          | Default

[17:27:45 ERROR]: [com.dfsek.terra.bukkit.TerraBukkitPlugin] TERRA HAS BEEN DISABLED

```
Errors occurred while registering commands.
Please report this to Terra.
cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:68) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        ... 10 more
Caused by: java.lang.IllegalStateException: Could not find Registry Registry field
        at cloud.commandframework.bukkit.internal.RegistryReflection.lambda$static$2(RegistryReflection.java:71) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
        at cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:71) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        ... 10 more
[17:27:45 INFO]: [Terra] Disabling Terra v6.2.1-BETA+358e09d05
```

**Comment by explorer3039** [comment]
can confirm in 1.19.3

**Comment by Astrashh** [comment]
1.19.3 isn't supported yet - you can view progress of development on the [1.19.3](https://github.com/PolyhedralDev/Terra/commits/dev/1.19.3) branch. Updating has not been as speedy as some of the other minor MC updates as 1.19.3 introduces a bunch of breaking internal changes, as well as it being holiday season. There will be no ETA on when this will be completed. Leaving this issue open until then.

**Comment by Ofloo** [comment]
Doesn't work here either says running v1.19.2 but that isn't true.
`[17:37:38 INFO]: [com.dfsek.terra.bukkit.TerraBukkitPlugin] Running on Minecraft version v1.19.2 with server implementation Paper.
[17:37:38 INFO]: [com.dfsek.terra.AbstractPlatform] Loading config packs...
[17:37:38 INFO]: [com.dfsek.terra.registry.master.ConfigRegistry] Loading ZIP archive: default.zip
[17:37:40 INFO]: [com.dfsek.terra.config.pack.ConfigPackImpl] Loading config pack "OVERWORLD:OVERWORLD"
[17:37:44 INFO]: [com.dfsek.terra.config.pack.ConfigPackImpl] Loaded config pack "OVERWORLD:OVERWORLD" v1.3.0 by Astrash, Sancires, Aureus in 5291.268929ms.
[17:37:44 INFO]: [com.dfsek.terra.AbstractPlatform] Loaded packs.
[17:37:44 ERROR]: [com.dfsek.terra.bukkit.TerraBukkitPlugin] TERRA HAS BEEN DISABLED

Errors occurred while registering commands.
Please report this to Terra.
cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[Terra.jar:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:68) ~[Terra.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.reload(CraftServer.java:1037) ~[paper-1.19.3.jar:git-Paper-345]
        at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:892) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:494) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:441) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-345]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra.jar:?]
        ... 18 more
Caused by: java.lang.IllegalStateException: Could not find Registry Registry field
        at cloud.commandframework.bukkit.internal.RegistryReflection.lambda$static$2(RegistryReflection.java:71) ~[Terra.jar:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
        at cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:71) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra.jar:?]
        ... 18 more
[17:37:44 INFO]: [Terra] Disabling Terra v6.2.1-BETA+358e09d05
`

**Comment by jacklollz2** [comment]
1.19.3 is now functional. Would love to see updates to the base Terra terrain to support the new blocks. Thanks.
