### ISSUE TITLE
error occured enabling terra 6.2.2 spigot 19.3

### ISSUE THREAD

**Issue by WoundedFighter** [PolyhedralDev/Terra#391]
## Pre-Issue Checklist

- [x ] I have checked that I am on the latest version of Terra.
- [x ] I have searched the github issue tracker for similar issues, including
  closed ones.
- [ x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x ] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [ x] I have attached a copy of the `latest.log` file
[latest.log](https://github.com/PolyhedralDev/Terra/files/10751057/latest.log)
- [ x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                | 
| Platform / Platform Version  | 
| Any External Plugins or Mods | 
| Terra Packs In Use           | 
| Terra Addons In Use          | 

## Issue Description

initial loading of server.

[20:23:47] [Server thread/ERROR]: Error occurred while enabling Terra v6.2.2-BETA+8fff27fdd (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.dfsek.terra.bukkit.nms.v1_19_R2.AwfulBukkitHacks.registerBiomes(AwfulBukkitHacks.java:38) ~[?:?]
	at com.dfsek.terra.bukkit.nms.v1_19_R2.NMSInitializer.initialize(NMSInitializer.java:12) ~[?:?]
	at com.dfsek.terra.bukkit.nms.Initializer.init(Initializer.java:20) ~[?:?]
	at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:95) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3650-Spigot-19641c7-7dbf862]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3650-Spigot-19641c7-7dbf862]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3650-Spigot-19641c7-7dbf862]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3650-Spigot-19641c7-7dbf862]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3650-Spigot-19641c7-7dbf862]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Could not find mappings in expected location.
	at xyz.jpenilla.reflectionremapper.ReflectionRemapper.forReobfMappingsInPaperJar(ReflectionRemapper.java:232) ~[?:?]
	at com.dfsek.terra.bukkit.nms.v1_19_R2.Reflection.<clinit>(Reflection.java:25) ~[?:?]
	... 13 more

### Steps to reproduce

load server
broken
stop server
start server
broken

### Expected behavior

loads with no error

### Actual behavior

[error](url)
### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```

```

</details>

**Comment by Astrashh** [comment]
Use [Paper](https://papermc.io/)

**Comment by WoundedFighter** [comment]
This plugin is posted in spigotmc.org, and your fix is use paper...?
