### ISSUE TITLE
[Bug] Terra is unable to load config files

### ISSUE THREAD

**Issue by nihiluis** [PolyhedralDev/Terra#393]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including
  closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value |
|------------------------------|-------|
| Terra Version                |  6.2.1 forge
| Platform / Platform Version  | 12.4.0
| Any External Plugins or Mods | Reproduces with just Terra, no mods needed
| Terra Packs In Use           | Default
| Terra Addons In Use          | Default

## Issue Description

Game crashes on startup.

### Steps to reproduce

1. Start the game with Terra and Forge. On Fabric the problem doesn't appear.

### Expected behavior

Game start

### Actual behavior

Game excepts on startup

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

```
[19:20:10] [modloading-worker-0/ERROR]: Error loading config.yml resource from jar
java.io.IOException: Cannot create directory './config/Terra'.
	at com.dfsek.terra.lib.commons.io.FileUtils.mkdirs(FileUtils.java:2200) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.lib.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.lib.commons.io.FileUtils.openOutputStream(FileUtils.java:2449) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.lib.commons.io.FileUtils.openOutputStream(FileUtils.java:2415) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.lib.commons.io.FileUtils.copyToFile(FileUtils.java:1042) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.lib.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:952) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.load(AbstractPlatform.java:127) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgePlatform.<init>(ForgePlatform.java:49) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgeEntryPoint.<clinit>(ForgeEntryPoint.java:51) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23392!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23391!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19:20:10] [modloading-worker-0/INFO]: Loading config values from config.yml
[19:20:10] [modloading-worker-0/ERROR]: Failed to load config
java.io.FileNotFoundException: ./config/Terra/config.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at com.dfsek.terra.config.PluginConfigImpl.load(PluginConfigImpl.java:81) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.load(AbstractPlatform.java:134) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgePlatform.<init>(ForgePlatform.java:49) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgeEntryPoint.<clinit>(ForgeEntryPoint.java:51) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23392!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23391!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19:20:10] [modloading-worker-0/ERROR]: Error while dumping resources...
java.nio.file.NoSuchFileException: ./config/Terra/addons
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[?:?]
	at java.nio.file.Files.walk(Files.java:3918) ~[?:?]
	at java.nio.file.Files.walk(Files.java:3973) ~[?:?]
	at com.dfsek.terra.AbstractPlatform.dumpResources(AbstractPlatform.java:231) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.load(AbstractPlatform.java:137) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgePlatform.<init>(ForgePlatform.java:49) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgeEntryPoint.<clinit>(ForgeEntryPoint.java:51) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23392!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23391!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19:20:10] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: terra, class com.dfsek.terra.forge.ForgeEntryPoint
java.lang.ExceptionInInitializerError: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23392!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23391!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: ./config/Terra/addons/bootstrap
	at com.dfsek.terra.addon.BootstrapAddonLoader.loadAddons(BootstrapAddonLoader.java:96) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.loadAddons(AbstractPlatform.java:180) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.load(AbstractPlatform.java:146) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgePlatform.<init>(ForgePlatform.java:49) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgeEntryPoint.<clinit>(ForgeEntryPoint.java:51) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	... 14 more
Caused by: java.nio.file.NoSuchFileException: ./config/Terra/addons/bootstrap
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:226) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[?:?]
	at java.nio.file.Files.walk(Files.java:3918) ~[?:?]
	at com.dfsek.terra.addon.BootstrapAddonLoader.loadAddons(BootstrapAddonLoader.java:88) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.loadAddons(AbstractPlatform.java:180) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.AbstractPlatform.load(AbstractPlatform.java:146) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgePlatform.<init>(ForgePlatform.java:49) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	at com.dfsek.terra.forge.ForgeEntryPoint.<clinit>(ForgeEntryPoint.java:51) ~[Terra-forge-6.2.1-BETA+358e09d05.jar%23367!/:6.2.1-BETA+358e09d05]
	... 14 more
```
[latest.log](https://github.com/PolyhedralDev/Terra/files/10777620/latest.log)

</details>

**Comment by solonovamax** [comment]
wait nvm, me and my 3 braincells missed it

**Comment by dfsek** [comment]
Terra is unable to create the config directory, this seems like a permission issue.
