### ISSUE TITLE
[Bug] StackOverflowError when generating terrain

### ISSUE THREAD

**Issue by kpAjun** [PolyhedralDev/Terra#451]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including
  closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it
  is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the
  pack I am using.
  
- [x] I have attached a copy of the `latest.log` file
- [x] I have filled out and provided all the appropriate information.

## Environment

| Name                         | Value                                                                                                                                                                       |
|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Terra Version                | 6.4.1-BETA-bukkit and 6.4.3-BETA-bukkit                                                                                                                 
| Platform / Platform Version  |  arclight-1.20.1-1.0.4-fd335c1
| Any External Plugins or Mods | LuckPerms,OpenInv,Vault,Multiverse-Core,ProtocolLib,Terra,WorldEdit,AdvancedAchievements,Flec toneChat,Novaconomy,WorldGuard, MythicNobs,MythicCrucible,EvenMoreFish,GSit,(following are mods),architectury,create,farmersdelight,yuushya
| Terra Packs In Use           | Default
| Terra Addons In Use          | None

## Issue Description

During terrain generation, the operation fails after throwing a long series of tracebacks.

### Steps to reproduce

1. Configure bukkit.yml as shown: ![HL)}K8ZI}~Q91IJ W(FE0BK](https://github.com/PolyhedralDev/Terra/assets/108323055/8dd254fd-ad40-41f2-903a-8217f645d910)
2. Command (mv create sub_world normal) or (mv create sub_world normal -g Terra:OVERWORLD), as shown in wiki.

### Expected behavior

Overworld generated without error.

### Full stacktrace

<details>
<summary>Exception Stacktrace</summary>

[21:41:58 FATAL] [Arclight]: Failed to schedule load callback for chunk [0, 0]
java.util.concurrent.CompletionException: java.lang.StackOverflowError
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.StackOverflowError
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:297) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:302) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:302) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:302) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:302) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.generator.CustomChunkGenerator.m_213609_(CustomChunkGenerator.java:302) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23168!/:arclight-1.20.1-1.0.4-fd335c1]
        at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGeneratorMixin.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23175!/:?]

</details>
……too long to submit, attached in file
[log.txt](https://github.com/PolyhedralDev/Terra/files/14203881/log.txt)

### Additional details

Using default JVM config on stack size when launching server.
MultiverseCore can create worlds without Terra.
First time submitting an issue. Please inform me if there is anything done wrong. Thank you very much!
[latest.log](https://github.com/PolyhedralDev/Terra/files/14203872/latest.log)

**Comment by kpAjun** [comment]
The stack trace is not uploaded successfully, here is the file.
[log.txt](https://github.com/PolyhedralDev/Terra/files/14203904/log.txt)

**Comment by kpAjun** [comment]
[UPDATE] It is confirmed that the above failure in the generation will lead to the server crashing if the player walks around and causes new chunks to generate in the overworld, as shown at the end of latest.log.

**Comment by justaureus** [comment]
We do not support any hybrid server platforms like arclight.

**Comment by solonovamax** [comment]
Please attempt to reproduce on either forge or paper.
