### ISSUE TITLE
No such config pack "DEFAULT"...

### ISSUE THREAD

**Issue by CodeKing09** [PolyhedralDev/Terra#58]
### Just errors upon errors when trying to generate world, tested both bukkit.yml generating and Multiverse2 (option to generate new world using generator plugin), NONE worked. I only use Terra, and MV2 (when testing if that would work).

**bukkit.yml error:**
`[17:39:41 INFO]: Preparing level "world"
[17:39:41 ERROR]: [Terra] Could not set generator for default world 'world': Plugin 'Terra v3.1.0-BETA+1ee2b18
java.lang.IllegalArgumentException: No such config pack "DEFAULT"
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.lambda$getDefaultWorldGenerator$3(TerraBukkitPlugin.java:162) ~[?:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_261]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.getDefaultWorldGenerator(TerraBukkitPlugin.java:161) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.getGenerator(CraftServer.java:1445) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:369) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**MV2 error:**
`[17:33:00 WARN]: [Multiverse-Core] Failed to get the default chunk generator: java.lang.IllegalArgumentException: No such config pack "DEFAULT"
[17:33:00 WARN]: [Multiverse-Core] This is a bug in Terra, NOT a bug in Multiverse!
[17:33:00 INFO]: Invalid generator! 'Terra:DEFAULT'. §cAborting world creation.
`

Help is appreciated! @dfsek

**Comment by dfsek** [comment]
> No such config pack "DEFAULT"
Look at config load time, correct any errors that occur during config load.
